import type { Video } from "./types";



export const MOCK_VIDEOS: Video[] = [
  {
    id: "1",
    title: "Building a Modern UI with React & Tailwind",
    thumbnailUrl: "https://picsum.photos/600/338?random=1",
    channelName: "Frontend Mastery",
    channelAvatarUrl: "https://picsum.photos/100/100?random=1",
    views: "120K",
    postedAt: "2 days ago",
    duration: "14:20",
  },
  {
    id: "2",
    title: "Minimalist Desk Setup Tour 2024",
    thumbnailUrl: "https://picsum.photos/600/338?random=2",
    channelName: "Tech Space",
    channelAvatarUrl: "https://picsum.photos/100/100?random=2",
    views: "850K",
    postedAt: "1 week ago",
    duration: "08:45",
  },
  {
    id: "3",
    title: "Learn TypeScript in 10 Minutes",
    thumbnailUrl: "https://picsum.photos/600/338?random=3",
    channelName: "Code Daily",
    channelAvatarUrl: "https://picsum.photos/100/100?random=3",
    views: "45K",
    postedAt: "5 hours ago",
    duration: "10:01",
  },
  {
    id: "4",
    title: "The Future of AI: What to Expect",
    thumbnailUrl: "https://picsum.photos/600/338?random=4",
    channelName: "Future Sight",
    channelAvatarUrl: "https://picsum.photos/100/100?random=4",
    views: "1.2M",
    postedAt: "3 weeks ago",
    duration: "22:15",
  },
  {
    id: "5",
    title: "Relaxing Lo-Fi Beats to Code To",
    thumbnailUrl: "https://picsum.photos/600/338?random=5",
    channelName: "Chill Hop",
    channelAvatarUrl: "https://picsum.photos/100/100?random=5",
    views: "3.4M",
    postedAt: "1 month ago",
    duration: "1:00:00",
  },
  {
    id: "6",
    title: "Day in the Life of a Software Engineer",
    thumbnailUrl: "https://picsum.photos/600/338?random=6",
    channelName: "Dev Vlog",
    channelAvatarUrl: "https://picsum.photos/100/100?random=6",
    views: "200K",
    postedAt: "4 days ago",
    duration: "12:30",
  },
  {
    id: "7",
    title: "Designing for Accessibility",
    thumbnailUrl: "https://picsum.photos/600/338?random=7",
    channelName: "UX Studio",
    channelAvatarUrl: "https://picsum.photos/100/100?random=7",
    views: "15K",
    postedAt: "1 day ago",
    duration: "18:00",
  },
  {
    id: "8",
    title: "Reviewing the New M3 Macbook Pro",
    thumbnailUrl: "https://picsum.photos/600/338?random=8",
    channelName: "Gadget Guru",
    channelAvatarUrl: "https://picsum.photos/100/100?random=8",
    views: "2.1M",
    postedAt: "2 months ago",
    duration: "15:45",
  },
   {
    id: "9",
    title: "Top 10 VS Code Extensions",
    thumbnailUrl: "https://picsum.photos/600/338?random=9",
    channelName: "Coding Tips",
    channelAvatarUrl: "https://picsum.photos/100/100?random=9",
    views: "98K",
    postedAt: "3 days ago",
    duration: "09:12",
  },
  {
    id: "10",
    title: "Cooking the Perfect Steak",
    thumbnailUrl: "https://picsum.photos/600/338?random=10",
    channelName: "Chef's Table",
    channelAvatarUrl: "https://picsum.photos/100/100?random=10",
    views: "4.5M",
    postedAt: "1 year ago",
    duration: "11:20",
  },
  {
    id: "11",
    title: "Mountain Biking Adventure",
    thumbnailUrl: "https://picsum.photos/600/338?random=11",
    channelName: "Outdoor Life",
    channelAvatarUrl: "https://picsum.photos/100/100?random=11",
    views: "320K",
    postedAt: "2 weeks ago",
    duration: "24:50",
  },
  {
    id: "12",
    title: "Abstract Art Painting Tutorial",
    thumbnailUrl: "https://picsum.photos/600/338?random=12",
    channelName: "Creative Corner",
    channelAvatarUrl: "https://picsum.photos/100/100?random=12",
    views: "56K",
    postedAt: "6 days ago",
    duration: "16:40",
  }
];

export const CATEGORIES = [
  "All",
  "Gaming",
  "Music",
  "Programming",
  "Podcasts",
  "News",
  "Live",
  "Sports",
  "Fashion",
  "Learning",
  "Beauty"
];
